class GameConstants:
	"""
	Static constants for the entire game. Do not modify.
	"""
	
	MAX_ROUNDS: int = 1000	
	MAX_TURNS: int = 2000
	BASE_MAX_STAMINA: int = 100	
	HILL_MAX_STAMINA_BONUS: int = 40	
	STAMINA_POWERUP_AMOUNT: int = 35	
	
	BASE_STAMINA_REGEN: int = 5	
	ADJACENT_REGEN_BONUS: int = 1	
	ADJACENCY_RADIUS: int = 1	
	BEACON_REGEN_BONUS: int = 3
	
	EXTRA_MOVE_COST: int = 10
	ERASE_STEP_EXTRA_COST: int = 15
	BEACON_COST: int = 25
	BEACON_REQUIREMENT_Q: int = 15
	BEACON_WINDOW_SIZE_P: int = 5
	BEACON_CONSUME_LEFTOVER_PAINT: int = 1

	MAX_PAINT_VALUE: int = 3
	PAINT_STAMINA_COST: int = 8
	PAINT_RANGE: int = 1
	HILL_CONTROL_THRESHOLD: float = 0.33
	BID_MAX: int = 50
	CONSTRUCT_TIME_LIMIT: float = 10.0
	BID_TIME_LIMIT: float = 20.0
	PLAY_TIME_LIMIT: float = 300.0
	COMMENTATE_TIME_LIMIT: float = 1.0

	TIME_TIEBREAK_THRESH = 5
	DOMINATION_WIN_THRESHOLD = .75

	ALLOW_DIAGONAL_MOVES: bool = False
